const mockBenchResources = [
  {
    id: "ben-001",
    name: "Aadhya Reddy",
    role: "Frontend Engineer",
    skills: ["React", "JavaScript", "REST APIs", "Tailwind"],
    proficiency: { React: "Expert", JavaScript: "Expert", "REST APIs": "Intermediate", Tailwind: "Intermediate" },
    category: "Ready",
    availability: 100,
    allocation: 0,
    lastAllocationDate: "2026-03-10",
    costPerDay: 2600,
    location: "Hyderabad",
    experience: 5,
    status: "active",
    noticePeriod: false,
    shadow: false,
    skillRelevance: 82,
    skillLastUsed: { React: "2026-02-15", JavaScript: "2026-02-15", "REST APIs": "2025-12-10", Tailwind: "2025-10-01" },
    missingSkills: ["TypeScript"],
    lastProject: { name: "Care Portal", client: "Winsmoke Sanji", endDate: "2026-03-10", reason: "Release completed" },
  },
  {
    id: "ben-002",
    name: "Bhargav Singh",
    role: "Java Backend Engineer",
    skills: ["Java", "Spring Boot", "Kafka"],
    proficiency: { Java: "Expert", "Spring Boot": "Expert", Kafka: "Intermediate" },
    availability: 80,
    allocation: 0,
    lastAllocationDate: "2026-02-20",
    costPerDay: 3200,
    location: "Pune",
    experience: 8,
    status: "active",
    noticePeriod: false,
    shadow: false,
    skillRelevance: 74,
    skillLastUsed: { Java: "2026-02-10", "Spring Boot": "2026-02-10", Kafka: "2025-11-01" },
    missingSkills: ["Microservices"],
    lastProject: { name: "Claim Central", client: "Westbridge", endDate: "2026-02-20", reason: "Budget hold" },
  },
  {
    id: "ben-003",
    name: "Charan Dev",
    role: "Data Engineer",
    skills: ["Python", "SQL", "Airflow"],
    proficiency: { Python: "Expert", SQL: "Expert", Airflow: "Intermediate" },
    availability: 65,
    allocation: 0,
    lastAllocationDate: "2026-01-29",
    costPerDay: 2800,
    location: "Bengaluru",
    experience: 7,
    status: "active",
    noticePeriod: false,
    shadow: false,
    skillRelevance: 71,
    skillLastUsed: { Python: "2025-12-02", SQL: "2025-12-02", Airflow: "2025-10-15" },
    missingSkills: ["dbt"],
    lastProject: { name: "Insight Grid", client: "Helios", endDate: "2026-01-29", reason: "Phase closed" },
  },
  {
    id: "ben-004",
    name: "Divya Nair",
    role: "DevOps Engineer",
    skills: ["AWS", "Terraform", "DevOps"],
    proficiency: { AWS: "Expert", Terraform: "Intermediate", DevOps: "Expert" },
    availability: 55,
    allocation: 0,
    lastAllocationDate: "2026-03-02",
    costPerDay: 3500,
    location: "Chennai",
    experience: 10,
    status: "active",
    noticePeriod: false,
    shadow: false,
    skillRelevance: 67,
    skillLastUsed: { AWS: "2026-01-11", Terraform: "2025-08-10", DevOps: "2026-01-11" },
    missingSkills: ["Kubernetes"],
    lastProject: { name: "Infra Mesh", client: "Apex", endDate: "2026-03-02", reason: "Stabilization complete" },
  },
  {
    id: "ben-005",
    name: "Eswar Rao",
    role: "QA Automation Engineer",
    skills: ["Selenium", "Java", "API Testing"],
    proficiency: { Selenium: "Expert", Java: "Intermediate", "API Testing": "Intermediate" },
    availability: 40,
    allocation: 0,
    lastAllocationDate: "2026-02-28",
    costPerDay: 1700,
    location: "Hyderabad",
    experience: 4,
    status: "active",
    noticePeriod: false,
    shadow: false,
    skillRelevance: 42,
    skillLastUsed: { Selenium: "2025-05-20", Java: "2025-05-20", "API Testing": "2025-05-20" },
    missingSkills: ["Playwright"],
    lastProject: { name: "Quality Sprint", client: "MediCore", endDate: "2026-02-28", reason: "Automation handed over" },
  },
  {
    id: "ben-006",
    name: "Farah Khan",
    role: "Full Stack Engineer",
    skills: ["React", "Node.js", "GraphQL"],
    proficiency: { React: "Expert", "Node.js": "Intermediate", GraphQL: "Intermediate" },
    availability: 90,
    allocation: 0,
    lastAllocationDate: "2026-03-18",
    costPerDay: 2950,
    location: "Mumbai",
    experience: 6,
    status: "active",
    noticePeriod: false,
    shadow: false,
    skillRelevance: 78,
    skillLastUsed: { React: "2026-02-19", "Node.js": "2026-02-19", GraphQL: "2025-12-01" },
    missingSkills: [],
    lastProject: { name: "Pulse App", client: "Nova", endDate: "2026-03-18", reason: "Release complete" },
  },
  {
    id: "ben-007",
    name: "Gowtham Varma",
    role: "Platform Engineer",
    skills: ["Kubernetes", "DevOps", "AWS"],
    proficiency: { Kubernetes: "Intermediate", DevOps: "Expert", AWS: "Intermediate" },
    availability: 100,
    allocation: 0,
    lastAllocationDate: "2026-02-01",
    costPerDay: 3600,
    location: "Bengaluru",
    experience: 9,
    status: "active",
    noticePeriod: false,
    shadow: false,
    skillRelevance: 69,
    skillLastUsed: { Kubernetes: "2025-01-10", DevOps: "2026-01-20", AWS: "2025-01-10" },
    missingSkills: ["Terraform"],
    lastProject: { name: "Ops Guard", client: "Nimbus", endDate: "2026-02-01", reason: "Transition finished" },
  },
  {
    id: "ben-008",
    name: "Harini Das",
    role: "Business Analyst",
    skills: ["Backlog Grooming", "JIRA"],
    proficiency: { "Backlog Grooming": "Expert", JIRA: "Expert" },
    availability: 30,
    allocation: 0,
    lastAllocationDate: "2026-03-05",
    costPerDay: 1400,
    location: "Pune",
    experience: 5,
    status: "active",
    noticePeriod: false,
    shadow: false,
    skillRelevance: 38,
    skillLastUsed: { "Backlog Grooming": "2026-01-03", JIRA: "2026-01-03" },
    missingSkills: ["Domain Discovery"],
    lastProject: { name: "Policy Tracker", client: "Aegis", endDate: "2026-03-05", reason: "Team resized" },
  },
  {
    id: "ben-009",
    name: "Ishaan Patel",
    role: "Python Engineer",
    skills: ["Python", "FastAPI", "SQL"],
    proficiency: { Python: "Expert", FastAPI: "Intermediate", SQL: "Intermediate" },
    availability: 75,
    allocation: 0,
    lastAllocationDate: "2025-12-15",
    costPerDay: 2500,
    location: "Ahmedabad",
    experience: 6,
    status: "active",
    noticePeriod: false,
    shadow: false,
    skillRelevance: 73,
    skillLastUsed: { Python: "2025-11-30", FastAPI: "2025-11-30", SQL: "2025-11-30" },
    missingSkills: ["Airflow"],
    lastProject: { name: "Decision Hub", client: "Zenith", endDate: "2025-12-15", reason: "Project paused" },
  },
  {
    id: "ben-010",
    name: "Jahnavi Kulkarni",
    role: "UI Engineer",
    skills: ["React", "Figma", "Tailwind"],
    proficiency: { React: "Intermediate", Figma: "Expert", Tailwind: "Intermediate" },
    availability: 85,
    allocation: 0,
    lastAllocationDate: "2026-03-12",
    costPerDay: null,
    location: "Hyderabad",
    experience: 4,
    status: "active",
    noticePeriod: false,
    shadow: false,
    skillRelevance: 62,
    skillLastUsed: { React: "2025-02-01", Figma: "2026-02-01", Tailwind: "2025-02-01" },
    missingSkills: ["Accessibility"],
    lastProject: { name: "Design System", client: "Verta", endDate: "2026-03-12", reason: "Contract closed" },
  },
  {
    id: "ben-011",
    name: "Karan Mehta",
    role: "Cloud Engineer",
    skills: ["AWS", "Terraform", "Ansible"],
    proficiency: { AWS: "Expert", Terraform: "Expert", Ansible: "Intermediate" },
    category: "Training",
    availability: 60,
    allocation: 0,
    lastAllocationDate: "2026-02-14",
    costPerDay: 3300,
    location: "Mumbai",
    experience: 11,
    status: "active",
    noticePeriod: false,
    shadow: false,
    skillRelevance: 58,
    skillLastUsed: { AWS: "2025-01-01", Terraform: "2025-01-01", Ansible: "2025-01-01" },
    missingSkills: ["Azure"],
    lastProject: { name: "Cloud Shift", client: "Axon", endDate: "2026-02-14", reason: "Migration complete" },
  },
  {
    id: "ben-012",
    name: "Lavanya Sri",
    role: "Data Analyst",
    skills: [],
    proficiency: {},
    availability: 95,
    allocation: 0,
    lastAllocationDate: "2026-01-30",
    costPerDay: 1200,
    location: "Chennai",
    experience: 3,
    status: "active",
    noticePeriod: false,
    shadow: false,
    skillRelevance: 25,
    skillLastUsed: {},
    missingSkills: ["SQL", "Power BI"],
    lastProject: { name: "Insight Lite", client: "Apex", endDate: "2026-01-30", reason: "Pilot finished" },
  },
  {
    id: "ben-013",
    name: "Madhav Jain",
    role: "Java Engineer",
    skills: ["Java", "Spring Boot", "REST APIs"],
    proficiency: { Java: "Expert", "Spring Boot": "Intermediate", "REST APIs": "Intermediate" },
    availability: 100,
    allocation: 0,
    lastAllocationDate: "2026-03-22",
    costPerDay: 2100,
    location: "Pune",
    experience: 5,
    status: "active",
    noticePeriod: false,
    shadow: false,
    skillRelevance: 76,
    skillLastUsed: { Java: "2026-02-28", "Spring Boot": "2026-02-28", "REST APIs": "2026-02-28" },
    missingSkills: [],
    lastProject: { name: "Care API", client: "Nova", endDate: "2026-03-22", reason: "Support completed" },
  },
  {
    id: "ben-014",
    name: "Nitya Sharma",
    role: "Scrum Master",
    skills: ["Scrum", "Facilitation", "JIRA"],
    proficiency: { Scrum: "Expert", Facilitation: "Expert", JIRA: "Intermediate" },
    availability: 25,
    allocation: 0,
    lastAllocationDate: "2026-02-07",
    costPerDay: 1900,
    location: "Delhi",
    experience: 9,
    status: "active",
    noticePeriod: false,
    shadow: false,
    skillRelevance: 35,
    skillLastUsed: { Scrum: "2025-06-10", Facilitation: "2025-06-10", JIRA: "2025-06-10" },
    missingSkills: ["Scaled Agile"],
    lastProject: { name: "Delivery Rhythm", client: "Helios", endDate: "2026-02-07", reason: "Program closed" },
  },
  {
    id: "ben-015",
    name: "Omkar Joshi",
    role: "DevOps Engineer",
    skills: ["Azure", "Terraform", "CI/CD"],
    proficiency: { Azure: "Intermediate", Terraform: "Intermediate", "CI/CD": "Expert" },
    availability: 70,
    allocation: 0,
    lastAllocationDate: "2025-12-22",
    costPerDay: 3100,
    location: "Bengaluru",
    experience: 8,
    status: "active",
    noticePeriod: false,
    shadow: false,
    skillRelevance: 61,
    skillLastUsed: { Azure: "2025-02-01", Terraform: "2025-02-01", "CI/CD": "2025-02-01" },
    missingSkills: ["AWS"],
    lastProject: { name: "Pipeline Hub", client: "MediCore", endDate: "2025-12-22", reason: "Portfolio shift" },
  },
  {
    id: "ben-016",
    name: "Pranav Kumar",
    role: "Support Engineer",
    skills: ["Incident Management", "SQL"],
    proficiency: { "Incident Management": "Expert", SQL: "Beginner" },
    availability: 15,
    allocation: 0,
    lastAllocationDate: "2026-03-17",
    costPerDay: 1100,
    location: "Hyderabad",
    experience: 2,
    status: "active",
    noticePeriod: false,
    shadow: false,
    skillRelevance: 20,
    skillLastUsed: { "Incident Management": "2025-09-01", SQL: "2025-09-01" },
    missingSkills: ["Root Cause Analysis"],
    lastProject: { name: "Support Desk", client: "Westbridge", endDate: "2026-03-17", reason: "Volume dropped" },
  },
  {
    id: "ben-017",
    name: "Qureshi Ali",
    role: "ML Engineer",
    skills: ["Python", "ML", "SQL"],
    proficiency: { Python: "Expert", ML: "Intermediate", SQL: "Intermediate" },
    availability: 85,
    allocation: 0,
    lastAllocationDate: "2026-02-25",
    costPerDay: 3400,
    location: "Bengaluru",
    experience: 7,
    status: "active",
    noticePeriod: false,
    shadow: false,
    skillRelevance: 72,
    skillLastUsed: { Python: "2025-11-15", ML: "2025-11-15", SQL: "2025-11-15" },
    missingSkills: ["MLOps"],
    lastProject: { name: "Model Studio", client: "Zenith", endDate: "2026-02-25", reason: "Use case delayed" },
  },
  {
    id: "ben-018",
    name: "Ritika Sen",
    role: "Frontend Engineer",
    skills: ["Angular", "TypeScript", "RxJS"],
    proficiency: { Angular: "Expert", TypeScript: "Expert", RxJS: "Intermediate" },
    availability: 100,
    allocation: 0,
    lastAllocationDate: "2025-11-20",
    costPerDay: 2400,
    location: "Kolkata",
    experience: 6,
    status: "active",
    noticePeriod: false,
    shadow: false,
    skillRelevance: 52,
    skillLastUsed: { Angular: "2024-10-10", TypeScript: "2024-10-10", RxJS: "2024-10-10" },
    missingSkills: ["React"],
    lastProject: { name: "Portal Refresh", client: "Verta", endDate: "2025-11-20", reason: "Account moved" },
  },
  {
    id: "ben-019",
    name: "Saanvi Gupta",
    role: "React Engineer",
    skills: ["React", "TypeScript", "Testing Library"],
    proficiency: { React: "Expert", TypeScript: "Intermediate", "Testing Library": "Intermediate" },
    availability: 100,
    allocation: 0,
    lastAllocationDate: "2026-03-21",
    costPerDay: 2700,
    location: "Hyderabad",
    experience: 5,
    status: "active",
    noticePeriod: false,
    shadow: false,
    skillRelevance: 84,
    skillLastUsed: { React: "2026-03-01", TypeScript: "2026-03-01", "Testing Library": "2026-03-01" },
    missingSkills: [],
    lastProject: { name: "Member Portal", client: "Winsmoke Sanji", endDate: "2026-03-21", reason: "Role closed" },
  },
  {
    id: "ben-020",
    name: "Tanmay Kuldeep",
    role: "Cloud Support",
    skills: ["AWS", "Linux", "Monitoring"],
    proficiency: { AWS: "Intermediate", Linux: "Expert", Monitoring: "Intermediate" },
    availability: 50,
    allocation: 0,
    lastAllocationDate: "2026-02-19",
    costPerDay: 1600,
    location: "Chennai",
    experience: 4,
    status: "active",
    noticePeriod: false,
    shadow: false,
    skillRelevance: 57,
    skillLastUsed: { AWS: "2025-03-12", Linux: "2025-03-12", Monitoring: "2025-03-12" },
    missingSkills: ["Terraform"],
    lastProject: { name: "Infra Support", client: "Aegis", endDate: "2026-02-19", reason: "Managed service ended" },
  },
  {
    id: "ben-021",
    name: "Uday Vyas",
    role: "L&D Pool Associate",
    skills: ["Python", "SQL", "Power BI"],
    proficiency: { Python: "Intermediate", SQL: "Intermediate", "Power BI": "Beginner" },
    category: "Training",
    availability: 60,
    allocation: 0,
    lastAllocationDate: "2026-01-18",
    costPerDay: 1300,
    location: "Pune",
    experience: 3,
    status: "active",
    noticePeriod: false,
    shadow: false,
    poolType: "Training",
    skillRelevance: 43,
    skillLastUsed: { Python: "2025-07-01", SQL: "2025-07-01", "Power BI": "2025-07-01" },
    missingSkills: ["Airflow"],
    lastProject: { name: "Analytics Support", client: "Nova", endDate: "2026-01-18", reason: "Moved to training pool" },
  },
  {
    id: "ben-022",
    name: "Vaishnavi Rao",
    role: "Architecture Pool Engineer",
    skills: ["Java", "System Design", "AWS"],
    proficiency: { Java: "Expert", "System Design": "Expert", AWS: "Intermediate" },
    category: "Shadow",
    availability: 45,
    allocation: 0,
    lastAllocationDate: "2026-02-04",
    costPerDay: 3900,
    location: "Bengaluru",
    experience: 12,
    status: "active",
    noticePeriod: false,
    shadow: false,
    poolType: "CoE",
    skillRelevance: 64,
    skillLastUsed: { Java: "2025-12-11", "System Design": "2025-12-11", AWS: "2025-12-11" },
    missingSkills: ["Kafka"],
    lastProject: { name: "Reference Architecture", client: "Helios", endDate: "2026-02-04", reason: "Moved to CoE pool" },
  },
  {
    id: "ben-023",
    name: "Waseem Ahmad",
    role: "R&D Engineer",
    skills: ["Python", "LLM", "FastAPI"],
    proficiency: { Python: "Expert", LLM: "Intermediate", FastAPI: "Intermediate" },
    category: "Training",
    availability: 55,
    allocation: 0,
    lastAllocationDate: "2025-12-30",
    costPerDay: 3000,
    location: "Hyderabad",
    experience: 6,
    status: "active",
    noticePeriod: false,
    shadow: false,
    poolType: "R&D",
    skillRelevance: 59,
    skillLastUsed: { Python: "2025-10-01", LLM: "2025-10-01", FastAPI: "2025-10-01" },
    missingSkills: ["Prompt Engineering"],
    lastProject: { name: "Innovation Lab", client: "Internal", endDate: "2025-12-30", reason: "Moved to R&D pool" },
  },
  {
    id: "ben-024",
    name: "Xena Joseph",
    role: "Notice Period Engineer",
    skills: ["React", "Node.js"],
    proficiency: { React: "Intermediate", "Node.js": "Intermediate" },
    availability: 100,
    allocation: 0,
    lastAllocationDate: "2026-03-10",
    costPerDay: 2200,
    location: "Delhi",
    experience: 4,
    status: "active",
    noticePeriod: true,
    shadow: false,
    skillRelevance: 75,
    skillLastUsed: { React: "2026-02-15", "Node.js": "2026-02-15" },
    missingSkills: [],
    lastProject: { name: "Notice Transition", client: "Apex", endDate: "2026-03-10", reason: "Resignation submitted" },
  },
  {
    id: "ben-025",
    name: "Yash Verma",
    role: "Inactive Engineer",
    skills: ["Java", "SQL"],
    proficiency: { Java: "Intermediate", SQL: "Intermediate" },
    availability: 100,
    allocation: 0,
    lastAllocationDate: "2026-01-01",
    costPerDay: 1500,
    location: "Pune",
    experience: 5,
    status: "inactive",
    noticePeriod: false,
    shadow: false,
    skillRelevance: 55,
    skillLastUsed: { Java: "2025-06-12", SQL: "2025-06-12" },
    missingSkills: [],
    lastProject: { name: "Historic Work", client: "Legacy", endDate: "2026-01-01", reason: "Employee inactive" },
  },
  {
    id: "ben-026",
    name: "Zoya Patel",
    role: "Shadow Resource",
    skills: ["React", "TypeScript"],
    proficiency: { React: "Intermediate", TypeScript: "Intermediate" },
    availability: 85,
    allocation: 0,
    lastAllocationDate: "2026-03-16",
    costPerDay: 2000,
    location: "Mumbai",
    experience: 3,
    status: "active",
    noticePeriod: false,
    shadow: true,
    skillRelevance: 65,
    skillLastUsed: { React: "2026-01-01", TypeScript: "2026-01-01" },
    missingSkills: [],
    lastProject: { name: "Shadow Sprint", client: "Nova", endDate: "2026-03-16", reason: "Shadow assignment" },
  },
  {
    id: "ben-002",
    name: "Duplicate Bhargav Singh",
    role: "Java Backend Engineer",
    skills: ["Java"],
    proficiency: { Java: "Expert" },
    availability: 100,
    allocation: 0,
    lastAllocationDate: "2026-03-10",
    costPerDay: 3000,
    location: "Pune",
    experience: 8,
    status: "active",
    noticePeriod: false,
    shadow: false,
    skillRelevance: 80,
    skillLastUsed: { Java: "2026-01-01" },
    missingSkills: [],
    lastProject: { name: "Duplicate Row", client: "Internal", endDate: "2026-03-10", reason: "Should be ignored" },
  },
];

export const getBenchResources = async () =>
  Promise.resolve({
    success: true,
    data: mockBenchResources,
  });
