// Helper to offset a date by N days from today
function daysFromNow(offset) {
  const d = new Date()
  d.setDate(d.getDate() + offset)
  return d.toISOString().split("T")[0]
}

function computeStatus(allocation) {
  if (allocation <= 20) return "available"
  if (allocation <= 70) return "partial"
  return "allocated"
}

// Realistic enterprise resource data with overlapping allocations, gaps, and tentative future work
const RESOURCE_DEFINITIONS = [
  {
    id: "res-001",
    name: "Aarav Sharma",
    avatar: "AS",
    role: "Technical Lead",
    skills: ["Architecture", "Java", "Microservices", "AWS", "Kafka"],
    location: "Bangalore",
    experience: 12,
    currentAllocation: 100,
    availableFrom: daysFromNow(47),
    currentProject: "Project Atlas",
    nextAssignment: "Project Keystone",
    employmentType: "Billable",
    utilizationHistory: [92, 88, 95, 100, 97, 100, 85, 90, 95, 100, 100, 98],
    allocationTimeline: [
      { project: "Project Genesis", startDate: daysFromNow(-180), endDate: daysFromNow(-95), allocation: 100 },
      { project: "Project Atlas", startDate: daysFromNow(-90), endDate: daysFromNow(47), allocation: 80 },
      { project: "Project Beacon", startDate: daysFromNow(-60), endDate: daysFromNow(10), allocation: 20 },
      { project: "Project Keystone", startDate: daysFromNow(50), endDate: daysFromNow(140), allocation: 100, tentative: true },
    ],
  },
  {
    id: "res-002",
    name: "Priya Chen",
    avatar: "PC",
    role: "Senior Frontend Engineer",
    skills: ["React", "TypeScript", "Next.js", "CSS", "GraphQL"],
    location: "Singapore",
    experience: 7,
    currentAllocation: 60,
    availableFrom: daysFromNow(12),
    currentProject: "Project Beacon",
    nextAssignment: "Under Review",
    employmentType: "Billable",
    utilizationHistory: [80, 75, 90, 85, 60, 70, 80, 85, 90, 75, 60, 65],
    allocationTimeline: [
      { project: "Project Catalyst", startDate: daysFromNow(-150), endDate: daysFromNow(-80), allocation: 100 },
      { project: "Project Beacon", startDate: daysFromNow(-70), endDate: daysFromNow(12), allocation: 60 },
      { project: "Project Nexus", startDate: daysFromNow(30), endDate: daysFromNow(90), allocation: 80, tentative: true },
    ],
  },
  {
    id: "res-003",
    name: "James Williams",
    avatar: "JW",
    role: "Backend Engineer",
    skills: ["Node.js", "Python", "PostgreSQL", "Redis", "Docker"],
    location: "New York",
    experience: 5,
    currentAllocation: 0,
    availableFrom: daysFromNow(0),
    currentProject: "Bench",
    nextAssignment: "TBD",
    employmentType: "Bench",
    utilizationHistory: [90, 85, 80, 70, 60, 40, 20, 0, 0, 0, 0, 0],
    allocationTimeline: [
      { project: "Project Delta", startDate: daysFromNow(-200), endDate: daysFromNow(-110), allocation: 100 },
      { project: "Project Echo", startDate: daysFromNow(-105), endDate: daysFromNow(-30), allocation: 80 },
    ],
  },
  {
    id: "res-004",
    name: "Sofia Rodriguez",
    avatar: "SR",
    role: "DevOps Engineer",
    skills: ["AWS", "Terraform", "Docker", "K8s", "CI/CD"],
    location: "Toronto",
    experience: 8,
    currentAllocation: 120,
    availableFrom: daysFromNow(65),
    currentProject: "Project Forge",
    nextAssignment: "Project Orbit",
    employmentType: "Billable",
    utilizationHistory: [95, 100, 105, 110, 100, 95, 100, 110, 115, 120, 120, 118],
    allocationTimeline: [
      { project: "Project Forge", startDate: daysFromNow(-120), endDate: daysFromNow(30), allocation: 80 },
      { project: "Project Horizon", startDate: daysFromNow(-30), endDate: daysFromNow(20), allocation: 40 },
      { project: "Project Orbit", startDate: daysFromNow(35), endDate: daysFromNow(120), allocation: 100, tentative: true },
    ],
  },
  {
    id: "res-005",
    name: "Liam Patel",
    avatar: "LP",
    role: "Full Stack Developer",
    skills: ["React", "Node.js", "MongoDB", "GraphQL", "AWS"],
    location: "London",
    experience: 4,
    currentAllocation: 40,
    availableFrom: daysFromNow(5),
    currentProject: "Project Catalyst",
    nextAssignment: "Project Lumen",
    employmentType: "Shadow",
    utilizationHistory: [30, 50, 60, 40, 35, 40, 45, 50, 40, 40, 38, 42],
    allocationTimeline: [
      { project: "Project Atlas", startDate: daysFromNow(-160), endDate: daysFromNow(-90), allocation: 80 },
      { project: "Project Catalyst", startDate: daysFromNow(-70), endDate: daysFromNow(5), allocation: 40 },
      { project: "Project Lumen", startDate: daysFromNow(8), endDate: daysFromNow(100), allocation: 100, tentative: true },
    ],
  },
  {
    id: "res-006",
    name: "Emma Johnson",
    avatar: "EJ",
    role: "QA Lead",
    skills: ["Selenium", "Cypress", "Jest", "TestRail", "API Testing"],
    location: "San Francisco",
    experience: 9,
    currentAllocation: 80,
    availableFrom: daysFromNow(25),
    currentProject: "Project Atlas",
    nextAssignment: "Project Prism",
    employmentType: "Billable",
    utilizationHistory: [85, 90, 88, 80, 82, 78, 80, 85, 88, 82, 80, 79],
    allocationTimeline: [
      { project: "Project Beacon", startDate: daysFromNow(-160), endDate: daysFromNow(-60), allocation: 100 },
      { project: "Project Atlas", startDate: daysFromNow(-55), endDate: daysFromNow(25), allocation: 80 },
      { project: "Project Prism", startDate: daysFromNow(30), endDate: daysFromNow(110), allocation: 60, tentative: true },
    ],
  },
  {
    id: "res-007",
    name: "Marcus Tanaka",
    avatar: "MT",
    role: "Cloud Architect",
    skills: ["AWS", "Azure", "GCP", "Terraform", "Serverless"],
    location: "Tokyo",
    experience: 14,
    currentAllocation: 50,
    availableFrom: daysFromNow(0),
    currentProject: "Project Horizon",
    nextAssignment: "Under Review",
    employmentType: "Billable",
    utilizationHistory: [70, 65, 55, 60, 50, 50, 55, 60, 50, 45, 50, 52],
    allocationTimeline: [
      { project: "Project Genesis", startDate: daysFromNow(-200), endDate: daysFromNow(-120), allocation: 100 },
      { project: "Project Horizon", startDate: daysFromNow(-90), endDate: daysFromNow(15), allocation: 50 },
    ],
  },
  {
    id: "res-008",
    name: "Yuki Kumar",
    avatar: "YK",
    role: "Data Engineer",
    skills: ["Python", "Spark", "Airflow", "SQL", "dbt"],
    location: "Bangalore",
    experience: 6,
    currentAllocation: 100,
    availableFrom: daysFromNow(55),
    currentProject: "Project Ion",
    nextAssignment: "Project Nexus",
    employmentType: "Billable",
    utilizationHistory: [100, 95, 100, 100, 98, 100, 100, 100, 95, 100, 100, 100],
    allocationTimeline: [
      { project: "Project Delta", startDate: daysFromNow(-170), endDate: daysFromNow(-85), allocation: 100 },
      { project: "Project Ion", startDate: daysFromNow(-80), endDate: daysFromNow(55), allocation: 100 },
      { project: "Project Nexus", startDate: daysFromNow(58), endDate: daysFromNow(150), allocation: 80, tentative: true },
    ],
  },
  {
    id: "res-009",
    name: "Ananya Garcia",
    avatar: "AG",
    role: "UX Designer",
    skills: ["Figma", "Research", "Prototyping", "A11y", "Design Systems"],
    location: "Berlin",
    experience: 6,
    currentAllocation: 30,
    availableFrom: daysFromNow(0),
    currentProject: "Project Beacon",
    nextAssignment: "TBD",
    employmentType: "Billable",
    utilizationHistory: [60, 45, 30, 50, 40, 35, 30, 30, 25, 30, 28, 32],
    allocationTimeline: [
      { project: "Project Catalyst", startDate: daysFromNow(-140), endDate: daysFromNow(-70), allocation: 80 },
      { project: "Project Beacon", startDate: daysFromNow(-50), endDate: daysFromNow(20), allocation: 30 },
    ],
  },
  {
    id: "res-010",
    name: "Carlos Hassan",
    avatar: "CH",
    role: "Mobile Developer",
    skills: ["React Native", "Swift", "Kotlin", "Flutter", "Firebase"],
    location: "Toronto",
    experience: 5,
    currentAllocation: 90,
    availableFrom: daysFromNow(35),
    currentProject: "Project Echo",
    nextAssignment: "Project Orbit",
    employmentType: "Billable",
    utilizationHistory: [75, 80, 85, 90, 88, 92, 90, 85, 88, 90, 92, 90],
    allocationTimeline: [
      { project: "Project Genesis", startDate: daysFromNow(-180), endDate: daysFromNow(-100), allocation: 60 },
      { project: "Project Atlas", startDate: daysFromNow(-100), endDate: daysFromNow(-50), allocation: 40 },
      { project: "Project Echo", startDate: daysFromNow(-45), endDate: daysFromNow(35), allocation: 90 },
      { project: "Project Orbit", startDate: daysFromNow(40), endDate: daysFromNow(130), allocation: 100, tentative: true },
    ],
  },
  {
    id: "res-011",
    name: "Fatima Smith",
    avatar: "FS",
    role: "ML Engineer",
    skills: ["Python", "TensorFlow", "PyTorch", "MLOps", "AWS SageMaker"],
    location: "London",
    experience: 7,
    currentAllocation: 0,
    availableFrom: daysFromNow(0),
    currentProject: "Bench",
    nextAssignment: "Project Keystone",
    employmentType: "Bench",
    utilizationHistory: [100, 95, 80, 60, 40, 20, 0, 0, 10, 0, 0, 0],
    allocationTimeline: [
      { project: "Project Forge", startDate: daysFromNow(-210), endDate: daysFromNow(-100), allocation: 100 },
      { project: "Project Ion", startDate: daysFromNow(-95), endDate: daysFromNow(-40), allocation: 60 },
      { project: "Project Keystone", startDate: daysFromNow(20), endDate: daysFromNow(110), allocation: 100, tentative: true },
    ],
  },
  {
    id: "res-012",
    name: "Noah Liu",
    avatar: "NL",
    role: "SRE",
    skills: ["Prometheus", "Grafana", "K8s", "Incident Mgmt", "Terraform"],
    location: "San Francisco",
    experience: 8,
    currentAllocation: 75,
    availableFrom: daysFromNow(18),
    currentProject: "Project Forge",
    nextAssignment: "Under Review",
    employmentType: "Billable",
    utilizationHistory: [80, 75, 70, 78, 82, 80, 75, 70, 72, 75, 78, 76],
    allocationTimeline: [
      { project: "Project Catalyst", startDate: daysFromNow(-160), endDate: daysFromNow(-80), allocation: 100 },
      { project: "Project Forge", startDate: daysFromNow(-75), endDate: daysFromNow(18), allocation: 75 },
    ],
  },
  {
    id: "res-013",
    name: "Mei Kovalenko",
    avatar: "MK",
    role: "Security Engineer",
    skills: ["OWASP", "Pen Testing", "IAM", "SOC2", "SIEM"],
    location: "Singapore",
    experience: 10,
    currentAllocation: 50,
    availableFrom: daysFromNow(0),
    currentProject: "Project Delta",
    nextAssignment: "Project Lumen",
    employmentType: "Billable",
    utilizationHistory: [60, 55, 50, 50, 48, 50, 55, 50, 45, 50, 50, 52],
    allocationTimeline: [
      { project: "Project Atlas", startDate: daysFromNow(-140), endDate: daysFromNow(-60), allocation: 80 },
      { project: "Project Delta", startDate: daysFromNow(-55), endDate: daysFromNow(30), allocation: 50 },
      { project: "Project Lumen", startDate: daysFromNow(35), endDate: daysFromNow(95), allocation: 70, tentative: true },
    ],
  },
  {
    id: "res-014",
    name: "Oleksii Anderson",
    avatar: "OA",
    role: "Staff Engineer",
    skills: ["System Design", "Go", "Distributed Systems", "gRPC", "AWS"],
    location: "Berlin",
    experience: 15,
    currentAllocation: 100,
    availableFrom: daysFromNow(60),
    currentProject: "Project Atlas",
    nextAssignment: "Project Nexus",
    employmentType: "Billable",
    utilizationHistory: [100, 100, 95, 100, 100, 100, 98, 100, 100, 100, 100, 100],
    allocationTimeline: [
      { project: "Project Horizon", startDate: daysFromNow(-200), endDate: daysFromNow(-90), allocation: 100 },
      { project: "Project Atlas", startDate: daysFromNow(-85), endDate: daysFromNow(60), allocation: 80 },
      { project: "Project Beacon", startDate: daysFromNow(-40), endDate: daysFromNow(15), allocation: 20 },
      { project: "Project Nexus", startDate: daysFromNow(65), endDate: daysFromNow(180), allocation: 100, tentative: true },
    ],
  },
  {
    id: "res-015",
    name: "Sarah Iyer",
    avatar: "SI",
    role: "Product Designer",
    skills: ["Figma", "Design Systems", "User Research", "Prototyping"],
    location: "Hyderabad",
    experience: 5,
    currentAllocation: 20,
    availableFrom: daysFromNow(0),
    currentProject: "Project Catalyst",
    nextAssignment: "TBD",
    employmentType: "Billable",
    utilizationHistory: [40, 30, 25, 20, 20, 15, 20, 25, 20, 18, 20, 22],
    allocationTimeline: [
      { project: "Project Echo", startDate: daysFromNow(-130), endDate: daysFromNow(-50), allocation: 60 },
      { project: "Project Catalyst", startDate: daysFromNow(-30), endDate: daysFromNow(40), allocation: 20 },
    ],
  },
  {
    id: "res-016",
    name: "Raj Brown",
    avatar: "RB",
    role: "Platform Engineer",
    skills: ["K8s", "Helm", "CI/CD", "ArgoCD", "Go"],
    location: "Bangalore",
    experience: 6,
    currentAllocation: 85,
    availableFrom: daysFromNow(28),
    currentProject: "Project Forge",
    nextAssignment: "Project Prism",
    employmentType: "Billable",
    utilizationHistory: [90, 85, 80, 88, 85, 82, 85, 88, 90, 85, 85, 84],
    allocationTimeline: [
      { project: "Project Delta", startDate: daysFromNow(-150), endDate: daysFromNow(-70), allocation: 100 },
      { project: "Project Forge", startDate: daysFromNow(-65), endDate: daysFromNow(28), allocation: 85 },
      { project: "Project Prism", startDate: daysFromNow(32), endDate: daysFromNow(120), allocation: 90, tentative: true },
    ],
  },
  {
    id: "res-017",
    name: "Olivia Kim",
    avatar: "OK",
    role: "Senior Frontend Engineer",
    skills: ["React", "TypeScript", "Vue.js", "Tailwind", "Storybook"],
    location: "Sydney",
    experience: 8,
    currentAllocation: 100,
    availableFrom: daysFromNow(40),
    currentProject: "Project Beacon",
    nextAssignment: "Project Orbit",
    employmentType: "Billable",
    utilizationHistory: [95, 100, 98, 100, 100, 95, 100, 100, 100, 100, 100, 100],
    allocationTimeline: [
      { project: "Project Genesis", startDate: daysFromNow(-170), endDate: daysFromNow(-80), allocation: 100 },
      { project: "Project Beacon", startDate: daysFromNow(-75), endDate: daysFromNow(40), allocation: 100 },
      { project: "Project Orbit", startDate: daysFromNow(45), endDate: daysFromNow(135), allocation: 80, tentative: true },
    ],
  },
  {
    id: "res-018",
    name: "Ahmed Singh",
    avatar: "AS2",
    role: "Backend Engineer",
    skills: ["Java", "Spring Boot", "PostgreSQL", "Kafka", "Docker"],
    location: "Hyderabad",
    experience: 6,
    currentAllocation: 110,
    availableFrom: daysFromNow(50),
    currentProject: "Project Ion",
    nextAssignment: "Under Review",
    employmentType: "Billable",
    utilizationHistory: [80, 85, 90, 95, 100, 105, 100, 110, 108, 110, 112, 110],
    allocationTimeline: [
      { project: "Project Ion", startDate: daysFromNow(-100), endDate: daysFromNow(50), allocation: 80 },
      { project: "Project Atlas", startDate: daysFromNow(-20), endDate: daysFromNow(30), allocation: 30 },
    ],
  },
  {
    id: "res-019",
    name: "Natasha Taylor",
    avatar: "NT",
    role: "Full Stack Developer",
    skills: ["React", "Python", "Django", "PostgreSQL", "AWS"],
    location: "New York",
    experience: 4,
    currentAllocation: 0,
    availableFrom: daysFromNow(0),
    currentProject: "Bench",
    nextAssignment: "Project Lumen",
    employmentType: "Bench",
    utilizationHistory: [70, 60, 50, 30, 10, 0, 0, 0, 0, 0, 0, 0],
    allocationTimeline: [
      { project: "Project Catalyst", startDate: daysFromNow(-180), endDate: daysFromNow(-100), allocation: 80 },
      { project: "Project Echo", startDate: daysFromNow(-95), endDate: daysFromNow(-50), allocation: 60 },
      { project: "Project Lumen", startDate: daysFromNow(15), endDate: daysFromNow(105), allocation: 100, tentative: true },
    ],
  },
  {
    id: "res-020",
    name: "David Nakamura",
    avatar: "DN",
    role: "Technical Lead",
    skills: ["Architecture", "Python", "Microservices", "GCP", "Terraform"],
    location: "Tokyo",
    experience: 11,
    currentAllocation: 70,
    availableFrom: daysFromNow(10),
    currentProject: "Project Horizon",
    nextAssignment: "Project Keystone",
    employmentType: "Billable",
    utilizationHistory: [80, 75, 70, 72, 68, 70, 72, 75, 70, 68, 70, 71],
    allocationTimeline: [
      { project: "Project Forge", startDate: daysFromNow(-160), endDate: daysFromNow(-80), allocation: 100 },
      { project: "Project Horizon", startDate: daysFromNow(-65), endDate: daysFromNow(10), allocation: 70 },
      { project: "Project Keystone", startDate: daysFromNow(14), endDate: daysFromNow(100), allocation: 100, tentative: true },
    ],
  },
]

export const RESOURCES = RESOURCE_DEFINITIONS.map((r) => ({
  ...r,
  status: computeStatus(r.currentAllocation),
}))

export { computeStatus }
