export const employeeMock = [
  {
    id: "10001",
    name: "Varshiniya",
    loginStatus: "Registered",
    loginDate: "08 Dec 2025",
    username: "varshiniya.ukkus",
    department: "Human Resources",
    location: "Hyderabad",
    workmode: "Remote",
    email: "varshiniya@company.com",
    emailStatus: "Active",
    designation: "HR Executive",
    manager: "Ramesh Kumar",
    doj: "12 May 2025",
    employeeType: "Full-Time",
    experience: "3 Years",
  },
  {
    id: "5100002",
    name: "Saladi Mohan",
    loginStatus: "Registered",
    loginDate: "13 May 2025",
    username: "mohan.saladi",
    department: "Engineering",
    location: "Hyderabad",
    workmode: "Remote",
    email: "mohan@company.com",
    emailStatus: "Active",
    designation: "Software Engineer",
    manager: "Sathish",
    doj: "13 May 2025",
    employeeType: "Full-Time",
    experience: "4 Years",

  },
  {
    id: "5100001",
    name: "Alwala Swarna Raj",
    employmentStatus: "Working",
    loginStatus: "Registered",
    loginDate: "08 Dec 2025",
    username: "swarnaraj.alwala",
    department: "Engineering",
    location: "Hyderabad",
    workmode: "Remote",
    email: "swarnaraj.alwala@pavestechnologies.com",
    emailStatus: "Active",
    designation: "Graduate Software Engineer",
    manager: "Sathish",
    doj: "08 Dec 2025",
    employeeType: "Full-Time",
    experience: "0-1 Years",
  },
  {
    id: "5100002",
    name: "Bhukya Ajay Kumar",
    employmentStatus: "Working",
    loginStatus: "Registered",
    loginDate: "08 Dec 2025",
    username: "ajay.bhukya",
    department: "Engineering",
    location: "Hyderabad",
    workmode: "onsite",
    email: "ajay.bhukya@pavestechnologies.com",
    emailStatus: "Active",
    designation: "Graduate Software Engineer",
    manager: "Sathish",
    doj: "08 Dec 2025",
    employeeType: "permanent",
    experience: "0-1 Years",
  },
  {
    id: "5100003",
    name: "Bolli Aditya Teja",
    employmentStatus: "Working",
    loginStatus: "Registered",
    loginDate: "08 Dec 2025",
    username: "aditya.bolli",
    department: "Engineering",
    location: "Hyderabad",
    workmode: "onsite",
    email: "aditya.bolli@pavestechnologies.com",
    emailStatus: "Active",
    designation: "Graduate Software Engineer",
    manager: "Sathish",
    doj: "08 Dec 2025",
    employeeType: "Full-Time",
    experience: "0-1 Years",
  },
  {
    id: "5100004",
    name: "Busam Lokeswari",
    employmentStatus: "Working",
    loginStatus: "Registered",
    loginDate: "08 Dec 2025",
    username: "lokeswari.busam",
    department: "Engineering",
    location: "Hyderabad",
    workmode: "onsite",
    email: "lokeswari.busam@pavestechnologies.com",
    emailStatus: "Active",
    designation: "Graduate Software Engineer",
    manager: "Sathish",
    doj: "08 Dec 2025",
    employeeType: "Full-Time",
    experience: "0-1 Years",
  },
  {
    id: "5100005",
    name: "Dama Rangaswamy",
    employmentStatus: "Working",
    loginStatus: "Registered",
    loginDate: "08 Dec 2025",
    username: "rangaswamy.dama",
    department: "Engineering",
    location: "Hyderabad",
    workmode: "Remote",
    email: "rangaswamy.dama@pavestechnologies.com",
    emailStatus: "Active",    
    designation: "Graduate Software Engineer",
    manager: "Sathish",
    doj: "08 Dec 2025",
    employeeType: "Contractual",
    experience: "0-1 Years",
  },
  {
    id: "5100006",
    name: "Gajula Thejas",
    employmentStatus: "Working",
    loginStatus: "Registered",
    loginDate: "08 Dec 2025",
    username: "thejas.gajula",
    department: "Engineering",
    location: "Hyderabad",
    workmode: "hybrid",
    email: "thejas.gajula@pavestechnologies.com",
    emailStatus: "Active",    
    designation: "Graduate Software Engineer",
    manager: "Sathish",
    doj: "08 Dec 2025",
    employeeType: "Contractual",
    experience: "0-1 Years",
  },
  {
    id: "5100007",
    name: "Gali Venkatesh",
    employmentStatus: "Working",
    loginStatus: "Registered",
    loginDate: "08 Dec 2025",
    username: "venkatesh.gali",
    department: "Engineering",
    location: "Hyderabad",
    workmode: "hybrid",
    email: "venkatesh.gali@pavestechnologies.com",
    emailStatus: "Active",   
    designation: "Graduate Software Engineer",
    manager: "Sathish",
    doj: "08 Dec 2025",
    employeeType: "Contractual",
    experience: "0-1 Years",
  },
  {
    id: "5100008",
    name: "Korada Ajay Kumar",
    employmentStatus: "Working",
    loginStatus: "Registered",
    loginDate: "08 Dec 2025",
    username: "ajay.korada",
    department: "Engineering",
    location: "Hyderabad",
    workmode: "hybrid",
    email: "ajay.korada@pavestechnologies.com",
    emailStatus: "Active",    
    designation: "Graduate Software Engineer",
    manager: "Sathish",
    doj: "08 Dec 2025",
    employeeType: "Full-Time",
    experience: "0-1 Years",
  },
  {
    id: "5100009",
    name: "Niharika Kandukoori",
    employmentStatus: "Working",
    loginStatus: "Registered",
    loginDate: "08 Dec 2025",
    username: "niharika.kandukoori",
    department: "Engineering",
    location: "Hyderabad",
    workmode: "hybrid",
    email: "niharika.kandukoori@pavestechnologies.com",
    emailStatus: "Active",    
    designation: "Graduate Software Engineer",
    manager: "Sathish",
    doj: "08 Dec 2025",
    employeeType: "intern",
    experience: "0-1 Years",
  },
  {
    id: "5100010",
    name: "Nuthula Ruchitha",
    employmentStatus: "Working",
    loginStatus: "Registered",
    loginDate: "08 Dec 2025",
    username: "ruchitha.nuthula",
    department: "Engineering",
    location: "Hyderabad",
    workmode: "hybrid",
    email: "ruchitha.nuthula@pavestechnologies.com",
    emailStatus: "Active",
    designation: "Graduate Software Engineer",
    manager: "Sathish",
    doj: "08 Dec 2025",
    employeeType: "intern",
    experience: "0-1 Years",
  },
];

