export const STATIC_ENUMS = {
    "FieldType": ["STRING", "LONG", "UUID", "ENUM", "BIG_DECIMAL", "LOCAL_DATE_TIME"],
    "AllocationStatus": ["PLANNED", "ACTIVE", "ENDED", "CANCELLED"],
    "DeliveryModel": ["ONSITE", "OFFSHORE", "HYBRID"],
    "PriorityLevel": ["LOW", "MEDIUM", "HIGH", "CRITICAL"],
    "RecordStatus": ["ACTIVE", "INACTIVE", "ON_HOLD"],
    "RiskLevel": ["LOW", "MEDIUM", "HIGH", "CRITICAL"],
    "AssetCategory": ["DEVICE", "SOFTWARE", "ACCESS", "TOOLS"],
    "AssetStatus": ["ACTIVE", "RETIRED", "INACTIVE", "LOST"],
    "ClientType": ["STRATEGIC", "STANDARD", "SUPPORT", "INTERNAL"],
    "ContactRole": ["DELIVERY_HEAD", "DELIVERY_MANAGER", "COMPLIANCE_OFFICER", "PROJECT_MANAGER", "ACCOUNT_MANAGER", "TECHNICAL_LEAD"],
    "EnablementAssignmentStatus": ["REQUESTED", "ASSIGNED", "IN_USE", "REJECTED", "RETURNED", "LOST"],
    "RequirementType": ["CERTIFICATION", "CLEARANCE", "TOOL_ACCESS", "SKILL"],
    "SLAType": ["NET_NEW", "REPLACEMENT", "BACKFILL", "EMERGENCY"],
    "DemandCommitment": ["SOFT", "CONFIRMED"],
    "DemandStatus": ["DRAFT", "REQUESTED", "APPROVED", "REJECTED", "CANCELLED"],
    "DemandType": ["NET_NEW", "REPLACEMENT", "BACKFILL", "EMERGENCY"],
    "EscalationLevel": ["LEVEL_1", "LEVEL_2", "EXECUTIVE"],
    "EscalationSource": ["INHERITED", "MANUAL"],
    "EscalationTriggerType": ["SLA_BREACH", "COMPLIANCE_FAILURE", "DELIVERY_RISK", "SECURITY_INCIDENT", "FINANCIAL_RISK"],
    "ProjectDataStatus": ["COMPLETE", "INCOMPLETE", "PENDING", "ERROR"],
    "ProjectStage": ["INITIATION", "PLANNING", "DESIGN", "DEVELOPMENT", "TESTING", "DEPLOYMENT", "MAINTENANCE", "COMPLETED", "MOBILIZATION", "EXECUTION", "STABILIZATION"],
    "ProjectStatus": ["ACTIVE", "APPROVED", "ARCHIVED", "PLANNING", "COMPLETED"],
    "StaffingReadinessStatus": ["NOT_READY", "UPCOMING", "READY", "MISSING"],
    "EmploymentStatus": ["ACTIVE", "ON_NOTICE", "EXITED"],
    "EmploymentType": ["FTE", "CONTRACTOR", "VENDOR"],
    "WorkforceCategory": ["INTERNAL", "VENDOR", "SHADOW"],
    "WorkingMode": ["WFO", "WFH", "HYBRID"],
    "CertificateStatus": ["ACTIVE", "EXPIRING_SOON", "EXPIRED"],
    "CertificateType": ["SKILL_BASED", "ACHIEVEMENT"],
    "TemplateStatus": ["DRAFT", "ACTIVE", "INACTIVE"]
};
